### ISSUE TITLE
OS X Settings

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#1]
We need to be able to set settings for OS X like the following:
  include osx::global::disable_key_press_and_hold
  include osx::global::expand_print_dialog
  include osx::global::expand_save_dialog
  include osx::dock::autohide
  include osx::finder::show_all_on_desktop
  include osx::finder::empty_trash_securely
  include osx::finder::unhide_library
  include osx::universal_access::ctrl_mod_zoom
  include osx::universal_access::enable_scrollwheel_zoom
  include osx::disable_app_quarantine
  include osx::no_network_dsstores
  include osx::keyboard::capslock_to_control

from: https://github.com/boxen/puppet-osx

**Comment by DanielOchoa** [comment]
Closed because of #17
