### ISSUE TITLE
Finish splitting up the common role

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#11]
Finish splitting common up into different roles. Need separate roles for each language we'll support along with one for "shell".

**Comment by DanielOchoa** [comment]
This is now closed by 3a627963f030b722acd85bb7d997d93c608161ad, f93e0815c480b0dbd99c526e3b572c8c0410d514 and cdcf80bb1eb8d45a30fc7603a5f3e9ecb33218de
