### ISSUE TITLE
Look through all non spf13 .bundle files and make sure we need everything

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#14]
We need to make sure that we don't have modules that are duplicates of things in spf13. Also, we should make sure we need everything extra we've added.

**Comment by DanielOchoa** [comment]
missing: 
- `jj` mapping to `<ESC>`
- `leader` map to `,`

**Comment by DanielOchoa** [comment]
I removed duplicated modules. Also, we are not using neovim, just plain 'ol vim.
