### ISSUE TITLE
Add irssi and asliases/config

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#22]
http://crunchbanglinux.org/wiki/irssi

Need to add:
- aliases to make it easy to use
- solarized color scheme

**Comment by DanielOchoa** [comment]
irssi check e1a1c52af79ca3cd443ee6de3f2e0656fc294425

**Comment by DanielOchoa** [comment]
aliases check 6cd6db6b80cabb31131bdbfadf3cc317d46690ef

**Comment by DanielOchoa** [comment]
solarized is the default color scheme for spf13. closing this issue.
