### ISSUE TITLE
Caps to control not working

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#25]
After a fresh provision, mapping caps to control isn't working.

**Comment by MatthewHager** [comment]
We might need to implement this how it is done here: https://github.com/boxen/puppet-osx/blob/master/manifests/keyboard/capslock_to_control.pp

**Comment by DanielOchoa** [comment]
this has been moved to its town repo https://github.com/poetic/short-stack-osx and it has been fixed.
