### ISSUE TITLE
Short stack should update itself

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#26]
It currently doesn't check for updates...

**Comment by DanielOchoa** [comment]
That would be a nice feature. Maybe we should work on this once 1.0 ships. yes?

**Comment by MatthewHager** [comment]
I'll knock this out. Should be pretty easy. Basically if the working copy is clean, it can do a pull. If it is dirty, that means you are probably working on it. If a dirty working copy is found it will warn the user and not update the project.
