### ISSUE TITLE
Vagrant isn't being installed

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#28]
I think something is wrong with the code that detects if an app exists. Vagrant is definitely in the apps list but doesn't get installed.

**Comment by DanielOchoa** [comment]
probably because it is installed as vagrant.pkg instead of .app.

**Comment by MatthewHager** [comment]
Can this be easily fixed?

**Comment by DanielOchoa** [comment]
yes. changed grep to `(.*)\.app|(.*)\.pkg` instead of just greping .app.

**Comment by DanielOchoa** [comment]
closed by f80afa7241c6c3a405403511194a3f86adc8dd02
