### ISSUE TITLE
Role idempotence

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#34]
From: https://servercheck.in/blog/testing-ansible-roles-travis-ci-github

Role idempotence

Another important test is the idempotence test—does the role change anything if it runs a second time? It should not, since all tasks you perform via Ansible should be idempotent (ensuring a static/unchanging configuration on subsequent runs with the same settings).

Run the role/playbook again, checking to make sure it's idempotent.
- >
  ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  | grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)
  This command runs the exact same command as before, but pipes the results through grep, which checks to make sure 'changed' and 'failed' both report 0. If there were no changes or failures, the idempotence test passes (and Travis sees the 0 exit and is happy), but if there were any changes or failures, the test fails (and Travis sees the 1 exit and reports a build failure).

**Comment by DanielOchoa** [comment]
TIL Idempotency. 

I realized this when setting up the fonts. each occurrence of an ansible run would just duplicate more fonts in the fonts dir.

**Comment by MatthewHager** [comment]
Great. I'm running on this thing. My fonts dir is probably huge. I'll prob do one more reformat for good measure once this thing is stable.

**Comment by DanielOchoa** [comment]
Also, I'm changing some of the descriptions for tasks to use 'ensure' instead of 'install', for example, ensure nsf13 is installed, instead of install nsf13. Since it is not actually installing it but making sure it is installed.

**Comment by MatthewHager** [comment]
To get SPF13 installed, we just need to run that curl command _unless it exists_. Secondarily, once it does exist (put task after that task), we need to ensure that the git repo is "latest". You can see the documentation here: http://docs.ansible.com/git_module.html. You should set the update flag to yes.

On the second task that keeps the repo up to date, set a handler to run the bundle install task. That way if it updates the repo bundle install will run.

**Comment by DanielOchoa** [comment]
I've already fixed this for spf13 on https://github.com/poetic/short-stack/commit/f71fc01a257d33cb334cfb45285c4db8b8d92d08. It is a clever fix, since it will also update spf13 if the remote SHA of the latest commit is different than the one on the current install. How cool is that?!

**Comment by MatthewHager** [comment]
I just closed this with 04576a24bd25b2c84f0437d7e6657d5dd69e83e9.
