### ISSUE TITLE
Current directory name and git branch for tmux powerline window name

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#4]
It would be awesome to make the window name that shows up in powerline for tmux the name of the current directory and git branch if applicable instead of it being the current running program (or perhaps show both if it isn't bash/zsh). I typically rename my windows to be the project I am working on and this is usually the current working directory.

There could be an issue if the window has splits because it would need to do one or the other. I'm opening this to start a conversation about what we think this should be.

**Comment by mantoni** [comment]
I'm looking for the same thing. Did you find anything?

**Comment by MatthewHager** [comment]
Yea, it works now. I honestly don't remember what I did. I think it is something in SPF13.
