### ISSUE TITLE
spf13 seems bloated to me

### ISSUE THREAD

**Issue by DanielOchoa** [poetic/short-stack#44]
It takes like 2 seconds to open. It has a lot of boilerplate to get it working on other systems we don't use/need (ex. windows). Do we really need it? Discuss.

**Comment by MatthewHager** [comment]
It seems fast enough to me. I like that we are cleanly forked where we can get their community updates and build on top of it. Maybe if SS takes off in the future we can discuss removing SPF. I agree that it isn't the prettiest codebase I've ever seen but it works.
