### ISSUE TITLE
When I tried to install short stack on Poetic iMac it did not succeed --- see following stack trace.

### ISSUE THREAD

**Issue by stefanlyew** [poetic/short-stack#50]
bash <(curl -s curl -L https://raw.githubusercontent.com/poetic/short-stack/master/install.sh)
Boostrapping your computer...
Installing pip...
Searching for pip
Best match: pip 6.1.1
Processing pip-6.1.1-py2.7.egg
pip 6.1.1 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
Installing ansible...
/dev/fd/11: line 30: pip: command not found

**Comment by MatthewHager** [comment]
I think this is because the computer is already using Boxen. If this comes back up with a computer not already using Boxen, we'll reopen.
