### ISSUE TITLE
Need to run :BundleInstall after fresh install

### ISSUE THREAD

**Issue by DanielOchoa** [poetic/short-stack#51]
This should be handled by short-stack.

**Comment by osxi** [comment]
@DanielOchoa this should already occur.

See: https://github.com/poetic/short-stack-vim/blob/master/handlers/main.yml

Note: I made a PR for replacing the deprecated commands (https://github.com/poetic/short-stack-vim/pull/1). `BundleInstall` is deprecated in favor of `PluginInstall` as per https://github.com/VundleVim/Vundle.vim/blob/master/doc/vundle.txt
