### ISSUE TITLE
Libreoffice url is broken

### ISSUE THREAD

**Issue by matt-wright86** [poetic/short-stack#52]
failed: [127.0.0.1] => (item=libreoffice) => {"failed": true, "item": "libreoffice"}
msg: Error: Download failed on Cask 'libreoffice' with message: Download failed: https://download.documentfoundation.org/libreoffice/stable/5.0.0/mac/x86_64/LibreOffice_5.0.0_MacOS_x86-64.dmg

**Comment by MatthewHager** [comment]
I've gone ahead and removed cask from the default setup. I'm thinking about not having cask at all as part of short-stack. I might make it a command-line/environment provisioning tool only.
